name: Release

on:
  push:
    branches:
      - main

jobs:
  filter-commits:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.filter.outputs.should-run }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensures all commits are fetched

      - name: Filter commits
        id: filter
        run: |
          # Initialize a flag to determine if we should run subsequent jobs
          SHOULD_RUN="false"

          # Loop through commit messages since last push
          for COMMIT_HASH in $(git rev-list ${{ github.event.before }}..${{ github.event.after }}); do
            COMMIT_MSG=$(git log -1 --format=%B $COMMIT_HASH)
            if [[ "$COMMIT_MSG" =~ ^(feat|fix): ]]; then
              SHOULD_RUN="true"
              break
            fi
          done

          echo "SHOULD_RUN=$SHOULD_RUN" >> $GITHUB_ENV
          echo "::set-output name=result::$SHOULD_RUN"

  release:
    needs: filter-commits
    if: needs.filter-commits.outputs.should-run == 'true'
    name: Release
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.8.1"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Release
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
